from typing import List, Optional
from pydantic import BaseModel, Field

# --- Health & Info Models ---
class HealthResponse(BaseModel):
    status: str = Field(..., example="healthy")
    openai_configured: bool = Field(..., example=True)
    chat_model: str = Field(..., example="gpt-4o-mini")
    embedding_model: str = Field(..., example="text-embedding-3-small")

class VideoInfoRequest(BaseModel):
    url_or_id: str = Field(..., description="YouTube video URL or 11-character video ID", example="https://www.youtube.com/watch?v=jXwOcpkMQAA")

class VideoInfoResponse(BaseModel):
    video_id: str = Field(..., example="jXwOcpkMQAA")
    title: str = Field(..., example="Attention is all you need")
    is_cached: bool = Field(..., example=False)

# --- Ingestion Models ---
class IngestRequest(BaseModel):
    url_or_id: str = Field(..., description="YouTube video URL or ID to ingest", example="https://www.youtube.com/watch?v=jXwOcpkMQAA")
    force_reindex: bool = Field(False, description="Whether to overwrite existing local index")

class IngestResponse(BaseModel):
    video_id: str = Field(..., example="jXwOcpkMQAA")
    title: str = Field(..., example="Attention is all you need")
    status: str = Field(..., example="success")
    is_fallback: bool = Field(..., example=False)
    message: str = Field(..., example="Video successfully indexed.")

# --- Chat & Query Models ---
class ChatRequest(BaseModel):
    url_or_id: str = Field(..., description="YouTube video URL or ID to query against", example="https://www.youtube.com/watch?v=jXwOcpkMQAA")
    question: str = Field(..., description="The question to ask the RAG system", example="What is this video about?")

class ChatResponse(BaseModel):
    video_id: str = Field(..., example="jXwOcpkMQAA")
    video_title: str = Field(..., example="Attention is all you need")
    question: str = Field(..., example="What is this video about?")
    answer: str = Field(..., description="Structured, timestamped response generated by LLM")
    is_fallback: bool = Field(..., example=False)

# --- Semantic Search Models ---
class SearchRequest(BaseModel):
    url_or_id: str = Field(..., description="YouTube video URL or ID", example="https://www.youtube.com/watch?v=jXwOcpkMQAA")
    query: str = Field(..., description="Search query for similarity retrieval", example="transformer architecture")
    k: int = Field(4, ge=1, le=20, description="Number of chunks to return")

class SearchChunk(BaseModel):
    chunk_index: int = Field(..., example=1)
    content: str = Field(..., example="[02:15] The Transformer uses self-attention mechanisms...")

class SearchResponse(BaseModel):
    video_id: str = Field(..., example="jXwOcpkMQAA")
    query: str = Field(..., example="transformer architecture")
    results_count: int = Field(..., example=4)
    chunks: List[SearchChunk]

# --- Index Management Models ---
class IndexItem(BaseModel):
    video_id: str = Field(..., example="jXwOcpkMQAA")
    index_path: str = Field(..., example="faiss_index/jXwOcpkMQAA")

class IndexListResponse(BaseModel):
    total_indexed: int = Field(..., example=2)
    indices: List[IndexItem]
